services:
  # Serviço Web (Django)
  - type: web
    name: sistema-reg-it
    env: python
    plan: free
    buildCommand: |
      pip install --upgrade pip
      pip install -r requirements.txt
      python manage.py collectstatic --noinput
      python manage.py migrate
    startCommand: gunicorn ColorAdmin.wsgi:application --bind 0.0.0.0:$PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: False
      - key: ALLOWED_HOSTS
        value: sistema-reg-it.onrender.com
      - key: DATABASE_URL
        fromDatabase:
          name: sistema-reg-it-db
          property: connectionString
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_ANON_KEY
        sync: false
      - key: SUPABASE_SERVICE_KEY
        sync: false

  # Banco de dados PostgreSQL
  - type: pserv
    name: sistema-reg-it-db
    plan: free
    env: postgresql
    ipAllowList: []
